name: docavailable-backend
region: fra
services:
  - name: backend
    github:
      branch: main
      deploy_on_push: true
      repo: your-username/your-repo
    build_command: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    run_command: |
      php artisan migrate --force
      php artisan storage:link
      php artisan optimize
      heroku-php-apache2 public/
    environment_slug: php
    envs:
      - key: APP_NAME
        value: DocAvailable
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DB_CONNECTION
        value: pgsql
      - key: CACHE_STORE
        value: redis
      - key: QUEUE_CONNECTION
        value: redis
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
databases:
  - name: db
    engine: PG
    version: "15"
